# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='percent_change',
            field=models.CharField(max_length=20),
        ),
    ]
