# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pse', '0002_auto_20160407_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
