# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pse', '0004_index_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='status',
            field=models.CharField(choices=[(b'OPEN', b'Open'), (b'CLOSED', b'Closed'), (b'RECESS', b'Recess')], default='OPEN', max_length=10),
        ),
    ]
